---
# LIST ALL Interfaces

- hosts: fusionservers #Inventory
  become: true #As a suoder
  vars_files: sshkeys.yml #File contain private key
  vars:
    ansible_ssh_private_key_file: "{{ defaultubuntu }}" #Private key path var
    const:
      apikey: '1924684565959'
  remote_user: ubuntu #Connect as

#List IP
  tasks:
  - name: Install python3
    apt:
      pkg:
      - python3
      - python3-pip

  - name: Install pynetbox
    pip:
      name: pynetbox

  - name: create a device in NetBox
    netbox_device:
#      private_key_file: /root/listipv2/cert.pem
      key_file: "/root/listipv2/cert.pem"
#      validate_certs: 0
      netbox_url: "https://netbox.ibanfirt.lan"
      netbox_token: "9712245587739acb26ec34005bc4ead4934e7568"
      data:
        name: "Test Device"
        device_type: "C9410R"
        device_role: "test"
        site: "BEANR"
      state: present
